version: '2'

services:
  app:
    image: webdevops/php-nginx
    ports:
       - "8080:80"
    links: [mysql]
    volumes:
      - .:/app:Z
    environment:
      - WEB_DOCUMENT_ROOT=/app/public
      - WEB_DOCUMENT_INDEX=/app.php

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    links:
      - mysql
    ports:
      - "8081:80"