version: '2'

services:
  app:
    image: webdevops/php-apache-dev:debian-9
    build: .
    ports:
      - "8080:80"

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    ports:
      - "8081:80"