version: '2'

services:
  app:
    image: webdevops/php-apache-dev:debian-9
    ports:
      - "8080:80"
    links:
      - mysql
    volumes:
      - ./src:/app/src:Z
      - ./public:/app/public:Z
      - ./vendor:/app/vendor:Z
    environment:
      - WEB_DOCUMENT_ROOT=/app/public

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    links:
      - mysql
    ports:
      - "8081:80"